### ISSUE TITLE
Adjust README file to refer to code_teams and potentially add up-front validation that it's set up

### ISSUE THREAD

**Issue by oskarpearson** [rubyatscale/modularization_statistics#14]
This gem expects the [RubyAtScale CodeOwnership Gem](https://github.com/rubyatscale/code_ownership) gem be configured to match the package.yml files in the repository

I wasn't aware of this, so blindly followed the README with a bit of cut-and-paste and received the message below.

What do people think about the following:

- Adjusting the README.md to tell people to configure the code_ownership gem first
- Checking that code_ownership has correctly been configured (either by https://github.com/rubyatscale/code_teams#configuration or just checking that `::CodeTeams.all` isn't empty)

```
  app_name: Rails.application.class.module_parent_name,
StandardError: Could not find team with name: `Range and Logistics` in components/alerting/slack/package.yml. Make sure the team is one of `[]`
```

The error is from https://github.com/rubyatscale/code_ownership/blob/130f20d6f2b447fb97611d57d2c0edfe4beed24b/lib/code_ownership/private.rb#L96-L103

**Comment by alexevanczuk** [comment]
That sounds great to me! Fully documenting how to set this up and all of its dependencies, even if that just means pointing to the code ownership README, sounds great). Happy to look at a PR for this 😄

**Comment by oskarpearson** [comment]
Note that I incorrectly said this gem depended on the CodeOwnership gem. It actually only depends on the CodeTeams gem.

I've added README.md updates to detail how package.yml should be configured, and that it should match the CodeTeams gem config
